/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DelegateRouteImport } from './routes/delegate'
import { Route as HandoffCardRouteImport } from './routes/handoff-card'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as EmailHandoffRouteImport } from './routes/email.handoff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DelegateRoute = DelegateRouteImport.update({
  id: '/delegate',
  path: '/delegate',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffCardRoute = HandoffCardRouteImport.update({
  id: '/handoff-card',
  path: '/handoff-card',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailHandoffRoute = EmailHandoffRouteImport.update({
  id: '/email/handoff',
  path: '/email/handoff',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delegate': typeof DelegateRoute
  '/handoff-card': typeof HandoffCardRoute
  '/learn': typeof LearnRoute
  '/students': typeof StudentsRoute
  '/thanks': typeof ThanksRoute
  '/email/handoff': typeof EmailHandoffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delegate': typeof DelegateRoute
  '/handoff-card': typeof HandoffCardRoute
  '/learn': typeof LearnRoute
  '/students': typeof StudentsRoute
  '/thanks': typeof ThanksRoute
  '/email/handoff': typeof EmailHandoffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/delegate': typeof DelegateRoute
  '/handoff-card': typeof HandoffCardRoute
  '/learn': typeof LearnRoute
  '/students': typeof StudentsRoute
  '/thanks': typeof ThanksRoute
  '/email/handoff': typeof EmailHandoffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/delegate'
    | '/handoff-card'
    | '/learn'
    | '/students'
    | '/thanks'
    | '/email/handoff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/delegate'
    | '/handoff-card'
    | '/learn'
    | '/students'
    | '/thanks'
    | '/email/handoff'
  id:
    | '__root__'
    | '/'
    | '/delegate'
    | '/handoff-card'
    | '/learn'
    | '/students'
    | '/thanks'
    | '/email/handoff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DelegateRoute: typeof DelegateRoute
  HandoffCardRoute: typeof HandoffCardRoute
  LearnRoute: typeof LearnRoute
  StudentsRoute: typeof StudentsRoute
  ThanksRoute: typeof ThanksRoute
  EmailHandoffRoute: typeof EmailHandoffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delegate': {
      id: '/delegate'
      path: '/delegate'
      fullPath: '/delegate'
      preLoaderRoute: typeof DelegateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff-card': {
      id: '/handoff-card'
      path: '/handoff-card'
      fullPath: '/handoff-card'
      preLoaderRoute: typeof HandoffCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/handoff': {
      id: '/email/handoff'
      path: '/email/handoff'
      fullPath: '/email/handoff'
      preLoaderRoute: typeof EmailHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DelegateRoute: DelegateRoute,
  HandoffCardRoute: HandoffCardRoute,
  LearnRoute: LearnRoute,
  StudentsRoute: StudentsRoute,
  ThanksRoute: ThanksRoute,
  EmailHandoffRoute: EmailHandoffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
